# Bài tập 2

### *Nguyễn Huỳnh Xuân Mai - 1712091*

## Câu 1 (1 điểm)

*Chạy một mô phỏng máy tính để kiếm được 1.000 đồng xu ảo. Lật mỗi đồng xu độc lập 10 lần. Tập trung vào 3 đồng xu như sau: c1 là đồng tiền đầu tiên, được đặt ngẫu nhiên từ 1.000 và cmin là đồng xu có tần số đầu tối thiểu (chọn loại tiền trước trong trường hợp hòa). Đặt v1, vrand, và vmin là số phần đầu thu được cho 3 đồng xu tương ứng trong số 10 lần tung.
Chạy thử nghiệm 100.000 lần để có được phân phối đầy đủ ν1, vrand và νmin (lưu ý rằng crand và cmin sẽ thay đổi từ chạy sang chạy).*

In [1]:
import numpy as np
import random

In [2]:
N = 10
mu = 0.5
n_repeats = 100000
n_coins = 1000

nus = np.random.binomial(N, mu, (n_repeats, n_coins)) / N

print(nus)

[[0.7 0.5 0.1 ... 0.8 0.7 0.6]
 [0.6 0.3 0.5 ... 0.5 0.4 0.2]
 [0.4 0.5 0.4 ... 0.5 0.5 0.5]
 ...
 [0.4 0.4 0.3 ... 0.2 0.7 0.3]
 [0.4 0.6 0.6 ... 0.5 0.3 0.4]
 [0.5 0.7 0.8 ... 0.7 0.4 0.4]]


In [3]:
print(nus[:, 0].reshape(-1,1))
i = random.randint(0,999)
print(i)
c_rand = nus[:, i]
print(c_rand.reshape(-1,1))
c1 = nus[:, 1]
print(c1.reshape(-1,1))

[[0.7]
 [0.6]
 [0.4]
 ...
 [0.4]
 [0.4]
 [0.5]]
156
[[0.4]
 [0.6]
 [0.5]
 ...
 [0.5]
 [0.7]
 [0.6]]
[[0.5]
 [0.3]
 [0.5]
 ...
 [0.4]
 [0.6]
 [0.7]]


In [4]:
cmin = np.min(nus, axis=1).reshape(-1,1)
cmin

array([[0. ],
       [0.1],
       [0.1],
       ...,
       [0. ],
       [0.1],
       [0.1]])

In [5]:
np.mean(cmin)

0.03734099999999999

In [6]:
c1mean = np.mean(c1)
c1mean

0.500515

In [7]:
crand_mean = np.mean(c_rand)
crand_mean

0.4991250000000001

#### ĐÁP ÁN LÀ
[b] 0.01 

## Câu 2 (1 điểm)

In [8]:
c1mean = np.mean(c1)
c1mean

0.500515

In [9]:
crand_mean = np.mean(c_rand)
crand_mean

0.4991250000000001

#### ĐÁP ÁN LÀ
[d] c1 and crand 

## Câu 3 (1 điểm)

- Đầu tiên, ta có hàm hypothesis là $h(x)$ mà ta muốn train trên hàm target $y = f(x)$ nhưng nó sẽ phát sinh lỗi với xác suất $\mu$. Sau khi tìm ra được $h(x)$, ta sẽ áp dụng $h(x)$ được tìm thấy đó cho một số noise data set (data trong thực tế).
- Xác suất mà $h(x)$ gây ra lỗi trong noise data là $\mu$ => xác suất mà $h(x)$ không gây ra lỗi trong noise data là $1 - \mu$.
- Xác suất mà khi ta làm sinh ra lỗi (do noise) là $1 - \lambda$ => xác suất noise không sinh ra lỗi là $\lambda$
- Vì tính toán là hàm nhị phân, nên xác suất gặp lỗi khi áp dụng $h(x)$ khi có noise của $f(x)$ là:
    - Xác suất sinh lỗi do noise: $P_1$ $=$ $1 - \lambda$
    - Xác suất không sinh lỗi do "deterministic": $P_2$ $=$ $1 - \mu$
    - Xác suất không sinh lỗi do noise: $P_3$ $=$ $\lambda$
    - Xác suất sinh lỗi do "deterministic": $P_4$ $=$ $\mu$
- Phân phối xác suất cho $\mu$ và $\lambda$ là thống kê độc lập.
- Vì thế:
    - $P_e$ $=$ $P_1$*$P_2$ + $P_3$*$P_4$
    - $P_e$ $=$ $(1 - \lambda)$*$(1 - \mu)$ + $\lambda$*$\mu$

#### ĐÁP ÁN LÀ
[e] (1−λ)∗(1−µ) + λ∗µ

## Câu 4 (1 điểm)

YOUR ANSWER HERE

## Câu 5 (1 điểm)

In [10]:
def generate_target_w():
    """
    Generates target_w (the vector of parameters of f) 
    from two random, uniformly distributed points in [-1, 1] x [-1, 1].
    
    Returns
    -------
    target_w : numpy array, shape (3, 1) 
        The vector of parameters of f.
    """
    # Generate two points from a uniform distribution over [-1, 1]x[-1, 1]
    p1 = np.random.uniform(-1, 1, 2)
    p2 = np.random.uniform(-1, 1, 2)
    # Compute the target W from these two points
    target_w = np.array([p1[1]*p2[0] - p1[0]*p2[1], p2[1] - p1[1], p1[0] - p2[0]]).reshape((-1, 1))
    
    return target_w

In [11]:
def generate_data(N, target_w):
    """
    Generates a data set by generating random inputs and then using target_w to generate the 
    corresponding outputs.
    
    Parameters
    ----------
    N : int
        The number of examples.
    target_w : numpy array, shape (3, 1) 
        The vector of parameters of f.
    
    Returns
    -------
    X : numpy array, shape (N, 3)
        The matrix of input vectors (each row corresponds to an input vector); the first column of 
        this matrix is all ones.
    Y : numpy array, shape (N, 1)
        The vector of outputs.        
    """
    bad_data = True # `bad_data = True` means: data contain points on the target line 
                    # (this rarely happens, but just to be careful)
                    # -> y's of these points = 0 (with np.sign); 
                    #    we don't want this (y's of data must be -1 or 1)
                    # -> re-generate data until `bad_data = False`
    
    while bad_data == True:
        X = np.random.uniform(-1, 1, (N, 2))
        X = np.hstack((np.ones((N, 1)), X)) # Add 'ones' column
        Y = np.sign(np.dot(X, target_w))
        if (0 not in Y): # Good data
            bad_data = False
    
    return X, Y

In [12]:
#n:  Repeat the experiment times
def LinearRegression(n, N):
    avg_error = 0.0
    for i in range (0, n):
        #Generate the vector of parameters of f
        target_w = generate_target_w()
        
        #Generates a data set
        X, Y = generate_data(N, target_w)
        
        #Find w
        X_dagger = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T)
        w = np.dot(X_dagger, Y)
        
        #Compute predictional output
        predictions = np.sign(np.dot(X, w))
        
        #Compute average error
        avg_error += np.mean(predictions!=Y)*1.0/n
        
    print('Trung binh loi: ', avg_error)

In [13]:
LinearRegression(1000, 100)

Trung binh loi:  0.0398599999999999


#### ĐÁP ÁN LÀ
[c] 0.01

## Câu 6 (1 điểm)

In [14]:
LinearRegression(1000, 1000)

Trung binh loi:  0.03860000000000003


#### ĐÁP ÁN LÀ
[c] 0.01

## Câu 7 (1 điểm)

In [15]:
def PLA(N):
    n_iterations = 0
    #Generate the vector of parameters of f
    target_w = generate_target_w()
    
    #Generates a data set
    X, Y = generate_data(N, target_w)
    
    #Find w
    X_dagger = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T)
    w = np.dot(X_dagger, Y)
    
    while(True):
        #Compute predictional output
        predictions = np.sign(np.dot(X, w))
        errs = np.sign(predictions - Y)
        
        #Compute mean error (giá trị độ lỗi nhị phân trung bình)
        mean_err = np.mean(predictions!=Y)
        
        #If mean error = 0, break out of the loop
        if mean_err == 0:
            break
            
        #Tinh chỉ số của một mẫu bị lỗi được chọn ngẫu nhiên, để tìm mảng các chỉ số của các mẫu bị lỗi
        rand_err_idx = np.flatnonzero(errs)
        
        #Chọn ra một giá trị ngẫu nhiên trong mảng các chỉ số
        i = np.random.choice(rand_err_idx)
        
        #Update w based on the fomular
        w = w + Y[i]*X[i].reshape(-1,1)
        
        #Update n_interations
        n_iterations += 1
        
    print('So lan hoi tu la: ', n_iterations)

In [16]:
PLA(10)

So lan hoi tu la:  2


#### ĐÁP ÁN LÀ
[a] 1

## Câu 8 (1 điểm)

In [17]:
def generate_target_f(X, ys):

    # Generate two points from a uniform distribution over [-1, 1]x[-1, 1]
    x1 = X[:, 1]
    x2 = X[:, 2]
    
    # Compute the target W from these two points
    target_f = np.sign(x1*x1 + x2*x2 - 0.6).reshape(ys.shape)
    
    return target_f

In [18]:
def Q8(N,n):
    avg_Ein = 0.0
    for i in range (0, n):
        #Generate w
        target_w = generate_target_w()
        
        #Generates a data set
        X, ys = generate_data(N, target_w)
        
        #Generate f
        y = generate_target_f(X, ys)
        
        #Generate data noise
        noise = np.random.choice(np.arange(N), size=int(0.1*N), replace=False)
        X_noise = X[noise]
        y_noise = -y[noise]
        X_use = np.concatenate((X, X_noise), axis = 0)
        Y_use = np.concatenate((y, y_noise), axis = 0)
        
        #Find w
        X_dagger = np.dot(np.linalg.inv(np.dot(X_use.T, X_use)), X_use.T)
        w = np.dot(X_dagger, Y_use)
        
        #Compute predictional output
        predictions = np.sign(np.dot(X_use, w))
        
        #Compute average error
        avg_Ein += np.mean(predictions!=Y_use)*1.0/n
    
    #Printf
    print('Trung binh E_in: ', avg_Ein)        

In [19]:
Q8(1000,1000)

Trung binh E_in:  0.50918


#### ĐÁP ÁN LÀ
[d] 0.5 

## Câu 9 (1 điểm)

In [20]:
def Q9(N, n):
    #Generate w
    target_w = generate_target_w()

    #Generates a data set
    X, ys = generate_data(N, target_w)   

    #Generate f
    ys = np.array([0])
    ys.resize(X.shape[0], 1)
    for i in range (0, X.shape[0]):
        ys[i] = np.sign(X[i][1]**2 + X[i][2]**2 - 0.6)

    random = np.random.choice(np.arange(ys.shape[0]), size=int(0.1*ys.shape[0]), replace=False)

    for i in range(0, random.size):
        ys[random[i]] = -ys[random[i]]

    T = np.array([])
    T.resize(ys.shape[0], 6)
    for i in range(0, ys.shape[0]):
        T[i][0] = X[i][0]
        T[i][1] = X[i][1]
        T[i][2] = X[i][2]
        T[i][3] = X[i][1]*X[i][2]
        T[i][4] = X[i][1]*X[i][1]
        T[i][5] = X[i][2]*X[i][2]

        X_dagger = np.dot(np.linalg.inv(np.dot(T.T, T)), T.T)
        w = np.dot(X_dagger, ys)

    print(w)

In [21]:
Q9(1000,1000)

[[-9.09664892e-01]
 [ 3.92455630e-03]
 [ 3.85209361e-02]
 [-1.01207849e-03]
 [ 1.42442395e+00]
 [ 1.55584078e+00]]


#### ĐÁP ÁN LÀ
[a] 

## Câu 10 (1 điểm)

In [22]:
def Q10(N, n, w):
    avg_error = 0.0
    for i in range(0, n):
        #Generate w
        target_w = generate_target_w()

        #Generates a data set
        X, ys = generate_data(N, target_w)   

        #Generate f
        ys = np.array([0])
        ys.resize(X.shape[0], 1)
        for i in range (0, X.shape[0]):
            ys[i] = np.sign(X[i][1]**2 + X[i][2]**2 - 0.6)

        random = np.random.choice(np.arange(ys.shape[0]), size=int(0.1*ys.shape[0]), replace=False)

        for i in range(0, random.size):
            ys[random[i]] = -ys[random[i]]

        T = np.array([])
        T.resize(ys.shape[0], 6)
        for i in range(0, ys.shape[0]):
            T[i][0] = X[i][0]
            T[i][1] = X[i][1]
            T[i][2] = X[i][2]
            T[i][3] = X[i][1]*X[i][2]
            T[i][4] = X[i][1]*X[i][1]
            T[i][5] = X[i][2]*X[i][2]
            X_dagger = np.dot(np.linalg.inv(np.dot(T.T, T)), T.T)
            w = np.dot(X_dagger, ys)
            

        predictions = np.dot(T, w)
        mean = np.mean(np.sign(predictions)!=ys)
        avg_error += (mean*1.0/n)
    print('Trung binh Eout: ', avg_error)

In [23]:
w = Q9(1000,1000)

Q10(1000, 1000, w)

[[-1.03986073]
 [ 0.04483643]
 [ 0.02871452]
 [ 0.15411305]
 [ 1.58562421]
 [ 1.69054184]]
Trung binh Eout:  0.12391899999999985


#### ĐÁP ÁN LÀ
[b] 0.1